######################################################################
##
## Filename: pulse_generator.udo
## Created on: Tue Oct 23 11:32:07 PM AUS Eastern Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
